# Generated by Django 6.0.5 on 2026-05-26 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=155)),
                ('business_phone', models.CharField(max_length=11)),
                ('description', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'agency',
                'verbose_name_plural': 'agencies',
            },
        ),
        migrations.CreateModel(
            name='AgencyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=122)),
                ('exact_address', models.TextField()),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'agency_address',
                'verbose_name_plural': 'agency_addresses',
            },
        ),
    ]
